name: Notificación de Cambios en Main

on:
  push:
    branches: [ "main" ]

jobs:
  notificar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -X POST \
          -H "Title: Nuevo cambio en el repositorio" \
          -H "Priority: default" \
          -d "El usuario ${{ github.actor }}  ha realizado un push en ${{ github.repository }}" \
          https://ntfy.sh/devops-itla